version: '3.4'
services:
  app:
    build:
      context: .
      dockerfile: /Users/admin/Documents/Developer/GoLang/lore_project/build/package/container/Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./app:/app
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    volumes:
      - ./data:/var/lib/postgresql/data